### ISSUE TITLE
error while following instructions in MAHRIO-MEDIUM here

### ISSUE THREAD

**Issue by EMCP** [JRGEMCP/MAHRIO-INSTRUCTOR#1]
While getting to the webpack build sequence on this repo, got some errors on the output

```
~/Dev/git/EMCP/JRGEMCP/MAHRIO-INSTRUCTOR (master)$ npm run dev
  0% compiling
Webpack is watching the files…

 29% building modules 162/168 modules 6 active .../@angular/forms/@angular/forms.es5.js[BABEL] Note: The code generator has deoptimised the styling of "/Users/emcp/Dev/git/EMCP/JRGEMCP/MAHRIO-INSTRUCTOR/node_modules/@angular/compiler/@angular/compiler.es5.js" as it exceeds the max of "500KB".
 47% building modules 316/320 modules 4 active ...P/MAHRIO-HEADER/src/services/index.jsModuleNotFoundError: Module not found: Error: Can't resolve '@ng-bootstrap/ng-bootstrap' in '/Users/emcp/Dev/git/EMCP/JRGEMCP/MAHRIO-HEADER/src'
    at factoryCallback (/Users/emcp/Dev/git/EMCP/JRGEMCP/MAHRIO-INSTRUCTOR/node_modules/webpack/lib/Compilation.js:264:39)
    at factory (/Users/emcp/Dev/git/EMCP/JRGEMCP/MAHRIO-INSTRUCTOR/node_modules/webpack/lib/NormalModuleFactory.js:247:20)
    at resolver (/Users/emcp/Dev/git/EMCP/JRGEMCP/MAHRIO-INSTRUCTOR/node_modules/webpack/lib/NormalModuleFactory.js:65:21)
    at asyncLib.parallel.e (/Users/emcp/Dev/git/EMCP/JRGEMCP/MAHRIO-INSTRUCTOR/node_modules/webpack/lib/NormalModuleFactory.js:138:21)
    at /Users/emcp/Dev/git/EMCP/JRGEMCP/MAHRIO-INSTRUCTOR/node_modules/async/dist/async.js:3861:9
    at /Users/emcp/Dev/git/EMCP/JRGEMCP/MAHRIO-INSTRUCTOR/node_modules/async/dist/async.js:421:16
    at iteratorCallback (/Users/emcp/Dev/git/EMCP/JRGEMCP/MAHRIO-INSTRUCTOR/node_modules/async/dist/async.js:996:13)
    at /Users/emcp/Dev/git/EMCP/JRGEMCP/MAHRIO-INSTRUCTOR/node_modules/async/dist/async.js:906:16
    at /Users/emcp/Dev/git/EMCP/JRGEMCP/MAHRIO-INSTRUCTOR/node_modules/async/dist/async.js:3858:13
    at resolvers.normal.resolve (/Users/emcp/Dev/git/EMCP/JRGEMCP/MAHRIO-INSTRUCTOR/node_modules/webpack/lib/NormalModuleFactory.js:130:23)
    at onError (/Users/emcp/Dev/git/EMCP/JRGEMCP/MAHRIO-INSTRUCTOR/node_modules/enhanced-resolve/lib/Resolver.js:65:10)
    at loggingCallbackWrapper (/Users/emcp/Dev/git/EMCP/JRGEMCP/MAHRIO-INSTRUCTOR/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at runAfter (/Users/emcp/Dev/git/EMCP/JRGEMCP/MAHRIO-INSTRUCTOR/node_modules/enhanced-resolve/lib/Resolver.js:158:4)
    at innerCallback (/Users/emcp/Dev/git/EMCP/JRGEMCP/MAHRIO-INSTRUCTOR/node_modules/enhanced-resolve/lib/Resolver.js:146:3)
    at loggingCallbackWrapper (/Users/emcp/Dev/git/EMCP/JRGEMCP/MAHRIO-INSTRUCTOR/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at next (/Users/emcp/Dev/git/EMCP/JRGEMCP/MAHRIO-INSTRUCTOR/node_modules/tapable/lib/Tapable.js:252:11)
    at /Users/emcp/Dev/git/EMCP/JRGEMCP/MAHRIO-INSTRUCTOR/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:40:4
    at loggingCallbackWrapper (/Users/emcp/Dev/git/EMCP/JRGEMCP/MAHRIO-INSTRUCTOR/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at runAfter (/Users/emcp/Dev/git/EMCP/JRGEMCP/MAHRIO-INSTRUCTOR/node_modules/enhanced-resolve/lib/Resolver.js:158:4)
    at innerCallback (/Users/emcp/Dev/git/EMCP/JRGEMCP/MAHRIO-INSTRUCTOR/node_modules/enhanced-resolve/lib/Resolver.js:146:3)
    at loggingCallbackWrapper (/Users/emcp/Dev/git/EMCP/JRGEMCP/MAHRIO-INSTRUCTOR/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at next (/Users/emcp/Dev/git/EMCP/JRGEMCP/MAHRIO-INSTRUCTOR/node_modules/tapable/lib/Tapable.js:252:11)
    at innerCallback (/Users/emcp/Dev/git/EMCP/JRGEMCP/MAHRIO-INSTRUCTOR/node_modules/enhanced-resolve/lib/Resolver.js:144:11)
    at loggingCallbackWrapper (/Users/emcp/Dev/git/EMCP/JRGEMCP/MAHRIO-INSTRUCTOR/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at next (/Users/emcp/Dev/git/EMCP/JRGEMCP/MAHRIO-INSTRUCTOR/node_modules/tapable/lib/Tapable.js:249:35)
    at resolver.doResolve.createInnerCallback (/Users/emcp/Dev/git/EMCP/JRGEMCP/MAHRIO-INSTRUCTOR/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:44:6)
    at loggingCallbackWrapper (/Users/emcp/Dev/git/EMCP/JRGEMCP/MAHRIO-INSTRUCTOR/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at afterInnerCallback (/Users/emcp/Dev/git/EMCP/JRGEMCP/MAHRIO-INSTRUCTOR/node_modules/enhanced-resolve/lib/Resolver.js:166:11)
    at loggingCallbackWrapper (/Users/emcp/Dev/git/EMCP/JRGEMCP/MAHRIO-INSTRUCTOR/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
    at next (/Users/emcp/Dev/git/EMCP/JRGEMCP/MAHRIO-INSTRUCTOR/node_modules/tapable/lib/Tapable.js:249:35)
resolve '@ng-bootstrap/ng-bootstrap' in '/Users/emcp/Dev/git/EMCP/JRGEMCP/MAHRIO-HEADER/src'
  Parsed request is a module
  using description file: /Users/emcp/Dev/git/EMCP/JRGEMCP/MAHRIO-HEADER/package.json (relative path: ./src)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: /Users/emcp/Dev/git/EMCP/JRGEMCP/MAHRIO-HEADER/package.json (relative path: ./src)
    resolve as module
      looking for modules in /Users/emcp/Dev/git/EMCP/JRGEMCP/MAHRIO-INSTRUCTOR/src
        using description file: /Users/emcp/Dev/git/EMCP/JRGEMCP/MAHRIO-INSTRUCTOR/package.json (relative path: ./src)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: /Users/emcp/Dev/git/EMCP/JRGEMCP/MAHRIO-INSTRUCTOR/package.json (relative path: ./src)
          using description file: /Users/emcp/Dev/git/EMCP/JRGEMCP/MAHRIO-INSTRUCTOR/package.json (relative path: ./src/@ng-bootstrap/ng-bootstrap)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /Users/emcp/Dev/git/EMCP/JRGEMCP/MAHRIO-INSTRUCTOR/src/@ng-bootstrap/ng-bootstrap doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/emcp/Dev/git/EMCP/JRGEMCP/MAHRIO-INSTRUCTOR/src/@ng-bootstrap/ng-bootstrap.js doesn't exist
            as directory
              /Users/emcp/Dev/git/EMCP/JRGEMCP/MAHRIO-INSTRUCTOR/src/@ng-bootstrap/ng-bootstrap doesn't exist
      looking for modules in /Users/emcp/Dev/git/EMCP/JRGEMCP/MAHRIO-INSTRUCTOR/node_modules
        using description file: /Users/emcp/Dev/git/EMCP/JRGEMCP/MAHRIO-INSTRUCTOR/package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: /Users/emcp/Dev/git/EMCP/JRGEMCP/MAHRIO-INSTRUCTOR/package.json (relative path: ./node_modules)
          using description file: /Users/emcp/Dev/git/EMCP/JRGEMCP/MAHRIO-INSTRUCTOR/package.json (relative path: ./node_modules/@ng-bootstrap/ng-bootstrap)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /Users/emcp/Dev/git/EMCP/JRGEMCP/MAHRIO-INSTRUCTOR/node_modules/@ng-bootstrap/ng-bootstrap doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/emcp/Dev/git/EMCP/JRGEMCP/MAHRIO-INSTRUCTOR/node_modules/@ng-bootstrap/ng-bootstrap.js doesn't exist
            as directory
              /Users/emcp/Dev/git/EMCP/JRGEMCP/MAHRIO-INSTRUCTOR/node_modules/@ng-bootstrap/ng-bootstrap doesn't exist


```

**Comment by JesusGuerrero** [comment]
This error is typical of node module not found

**Comment by JesusGuerrero** [comment]
let's ignore mahrio-instructor for the time being. We'll come back to it when we have our first use case for it. Right now want to get the student account working so they can create tutorials of their work to show anyone who is anonymous
